name: TameManagement
main: com.etriacraft.tamemanagement.TameManagement
version: 1.4.0-SNAPSHOT 1
author: MistPhizzle
softdepend: [GriefPrevention]
commands:
  tame:
permissions:
  tamemanagement.admin:
    default: op
    children:
      tamemanagement.reload: true
      tamemanagement.setowner: true
      tamemanagement.release: true
      tamemanagement.horse.setcolor: true
      tamemanagement.horse.setvariant: true
      tamemanagement.protecthorses.override: true
      tamemanagement.invoke: true